# Desktop-specific configuration

# Monitors
monitor=DP-2,3840x2160@160,0x0,1.5
monitor=HDMI-A-1,1920x1080@60,2560x0,1

# Environment variables
env = XDG_MENU_PREFIX,arch-
env = ELECTRON_OZONE_PLATFORM_HINT,auto
env = QT_QPA_PLATFORMTHEME,gtk3
env = QT_QPA_PLATFORMTHEME_QT6,gtk3

# Input
input {
    kb_layout = us
    kb_variant = altgr-intl
}

# General
general {
    gaps_out = 3,10,10,10
}


# Decoration
decoration {
    shadow {
        range = 4
    }
}

# Workspace settings
workspace = 2, monitor:DP-2
workspace = 1, monitor:HDMI-A-1
workspace = s[true], gapsout:100, gapsin:0

# Binds
bind = SUPER SHIFT, T, exec, ghostty #open the terminal
bind = SUPER, RETURN, exec, pkill wofi || wofi # Show the graphical app launcher
bind = SUPER SHIFT, RETURN, exec, ~/.config/hypr/scripts/capture-menu # Capture menu (screenshot, screenrecord, color picker)
