[mgr]
ratio          = [ 1, 3, 4 ]
sort_by        = "mtime"
sort_sensitive = false
sort_reverse 	 = true
sort_dir_first = true
sort_translit  = false
linemode       = "none"
show_hidden    = false
show_symlink   = true
scrolloff      = 5
mouse_events   = [ "click", "scroll" ]
title_format   = "Yazi: {cwd}"

[preview]
wrap            = "no"
tab_size        = 2
max_width       = 1000
max_height      = 1000
cache_dir       = ""
image_delay     = 30
image_filter    = "triangle"
image_quality   = 75
ueberzug_scale  = 1
ueberzug_offset = [ 0, 0, 0, 0 ]

[[plugin.prepend_fetchers]]
url   = "*"
run   = "git"
group = "git"

[[plugin.prepend_fetchers]]
url   = "*/"
run   = "git"
group = "git"

[[plugin.prepend_previewers]]
mime = "application/sqlite3"
run = '''
piper -- sh -c '
echo "== Row counts ==" &&
for t in $(sqlite3 "$1" ".tables"); do
    printf "%-20s " "$t"
    sqlite3 "$1" "SELECT COUNT(*) FROM \"$t\";"
done
' sh "$1"
'''
[[plugin.prepend_previewers]]
url = "*.md"
run = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"'

[[plugin.prepend_previewers]]
url = "*.csv"
run = """piper -- column -t -s, "$1" | awk 'NR==1{print "\\033[1;4m" $0 "\\033[0m"; next} {print}'"""

[opener]
sqlite = [
    { run = 'sqlite3 %s', desc= "sqlite3", block = true }
]
csvlens = [
    { run = 'csvlens %s', desc= "csvlens", block = true }
]

[open]
prepend_rules = [
	{url = "*.db", use = "sqlite"},
	{url = "*.csv", use = ["csvlens", "edit"]},
]
