wallpaper {
    monitor = HDMI-A-1
    path = /home/till/.config/hypr/wallpapers/wallhalla-64.png 
    fit_mode = cover
}

wallpaper {
    monitor = eDP-1
    path = /home/till/.config/hypr/wallpapers/wallhalla-64.png 
    fit_mode = cover
}

splash = false
