# ThinkPad-specific configuration

# Monitors
monitor=eDP-1,1920x1080@60,0x0,1.2

# Input
input {
    kb_layout = de
}

# General
general {
    gaps_out = 7,10,10,10
}

# Decoration
decoration {
    shadow {
        range = 2
        color = rgba(1a1a1aee)
    }
}

# Workspace settings
workspace = s[true], gapsout:50, gapsin:0

# Binds
bind = SUPER, SPACE, exec, pkill wofi || wofi # Show the graphical app launcher
bind = SUPER SHIFT, SPACE, exec, ~/.config/hypr/scripts/capture-menu # Capture menu (screenshot, screenrecord, color picker)
