#!/bin/bash

OUTPUT_NAME="eDP-1"

if [ $(hyprctl monitors -j | jq ".[]|select(.name==\"$OUTPUT_NAME\").dpmsStatus") = "true" ]; then 
  swaylock
else
  hyprctl dispatch dpms on $OUTPUT_NAME
  swaylock
  sleep 5
  hyprctl dispatch dpms off $OUTPUT_NAME
fi

