$SCRIPT = ~/.config/hypr/scripts

bind = , xf86audioraisevolume, exec, swayosd-client --output-volume raise --monitor "$(hyprctl monitors -j | jq -r '.[] | select(.focused == true).name')" #$SCRIPT/volume --inc 
bind = , xf86audiolowervolume, exec, swayosd-client --output-volume lower --monitor "$(hyprctl monitors -j | jq -r '.[] | select(.focused == true).name')"
bind = , xf86AudioMicMute, exec, $SCRIPT/volume --toggle-mic 
bind = , xf86audioMute, exec, $SCRIPT/volume --toggle 

bind = , xf86KbdBrightnessDown, exec, $SCRIPT/kb-brightness --dec 
bind = , xf86KbdBrightnessUp, exec, $SCRIPT/kb-brightness --inc 

bind = , xf86MonBrightnessDown, exec, $SCRIPT/brightness --dec 
bind = , xf86MonBrightnessUp, exec, $SCRIPT/brightness --inc 
